swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get all transactions API
      description: API for fetching all transactions of a user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transactions retrieved successully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "401":
          description: Invalid Token
        "500":
          description: Internal Server Error
  /user/transactions/{year}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get transaction of a specific year API
      description: API for fetching all transactions of a user for the current year
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: year
          description: year to fetch
          required: true
          type: number
      produces:
        - application/json
      responses:
        "200":
          description: Transactions retrieved successully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Invalid Field (year)
        "401":
          description: Invalid Token
        "500":
          description: Internal Server Error
  /user/transactions/{year}/{month}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get transaction of a specific month API
      description: API for fetching all transactions of a user for the current month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: year
          description: year to fetch
          required: true
          type: number
        - in: path
          name: month
          description: month to fetch
          required: true
          type: number
      produces:
        - application/json
      responses:
        "200":
          description: Transactions retrieved successully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Invalid Fields (Year/Month)
        "401":
          description: Invalid Token
        "500":
          description: Internal Server Error
  /user/transaction:
    post:
      tags:
        - Transaction Module
      summary: Create new transaction for an user
      description: API for creating new transaction for an user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Create transaction Payload
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "201":
          description: Create new transaction Successfully
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Invalid Token
        "500":
          description: Internal Server Error
  /user/transaction/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get transaction Details API
      description: API for fetching a particular transaction of a user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: ID of transaction to fetch
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transactions retrieved successully
          schema:
            $ref: "#/definitions/TransactionDetailsResponse"
        "400":
          description: Invalid Field (ID)
        "401":
          description: Invalid Token
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transaction Details API
      description: API for updating a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: id of the transaction
          required: true
          type: string
        - in: body
          name: body
          description: informations to be updated
          required: true
          schema:
            $ref: "#/definitions/TransactionDetailsUpdate"
      produces:
        - application/json
      responses:
        "201":
          description: Transaction informations updated successully
          schema:
            $ref: "#/definitions/TransactionDetailsResponse"
        "400":
          description: Invalid Fields (ID || body)
        "401":
          description: Invalid Token
        "500":
          description: Internal Server Error
    delete:
      tags:
        - Transaction Module
      summary: Delete transaction Details API
      description: API for removing extra transaction informations (type,category,notes)
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: ID of the transaction that needs informations to be deleted
          required: true
          type: string
      responses:
        "204":
          description: Transaction informations removed successully
        "400":
          description: Invalid ID supplied
        "401":
          description: Invalid Token
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transaction:
    properties:
      items:
        type: object
        properties:
          year:
            type: number
            description: year of the transaction
          month:
            type: number
            description: month of the transaction
          day:
            type: number
            description: day of the transaction
          title:
            type: string
            description: title of the transaction
          description:
            type: string
            description: description of the transaction
          amount:
            type: number
            description: amount of the transaction
          balance:
            type: number
            description: balance of the transaction
          type:
            type: string
            description: type of the transaction
          category:
            type: string
            description: category of the transaction
          notes:
            type: string
            description: notes on the transaction
  TransactionsYear:
    type: object
    properties:
      year:
        type: number
  TransactionsMonth:
    type: object
    properties:
      year:
        type: number
      month:
        type: number
  TransactionDetails:
    type: object
    properties:
      id:
        type: string
  TransactionDetailsUpdate:
    type: object
    properties:
      type:
        type: string
      category:
        type: string
      notes:
        type: string
  TransactionDetailsDelete:
    type: object
    properties:
      id:
        type: string
  TransactionResponse:
    properties:
      items:
        type: object
        properties:
          status:
            type: integer
          message:
            type: string
          body:
            type: object
            properties:
              id:
                type: string
                description: id of the new transaction created
              title:
                type: string
                description: title of the transaction
  TransactionsResponse:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        year:
          type: number
        month:
          type: number
        title:
          type: string
        amountTotal:
          type: number
  TransactionDetailsResponse:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      amountTotal:
        type: number
      year:
        type: number
      month:
        type: number
      day:
        type: number
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      type:
        type: string
      category:
        type: string
      notes:
        type: string
